# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.public]
file = "crates/db/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[print_schema.smes]
schema = "smes"
file = "crates/db/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/Users/sejunpark/Documents/IT/bspl/migrations"
