### Get the captcha image
# Cookies are preserved between requests
GET /venturein/pbntc/captchaImg.do HTTP/1.1
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,ko-KR;q=0.8,ko;q=0.7,id;q=0.6
Connection: keep-alive
Host: www.smes.go.kr
Referer: https://www.smes.go.kr/venturein/pbntc/searchVntrCmp
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
dnt: 1
sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-gpc: 1

#Set-Cookie: SESSION_TTL=20241003172138; Max-Age=1800; Expires=Thu, 03-Oct-2024 08:21:38 GMT; Path=/; Secure
#Set-Cookie: SMESSESSION=52631aca-0a20-4edc-bcce-3984f073a630; Path=/venturein/; HttpOnly
#Set-Cookie: __VCAP_ID__=e5ecb9bb-7173-4d57-57c2-360b; Path=/venturein; HttpOnly


### Submit the answer
# Cookies are preserved between requests.
# You have to send the corresponding cookie information of the original captcha image request.
# The server seems to store the captcha answer based on the session information
# responded for the original captcha image request.
GET /venturein/pbntc/searchVntrCmpDtls?vniaSn=1097842&captcha=043375 HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,ko-KR;q=0.8,ko;q=0.7,id;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Host: www.smes.go.kr
Pragma: no-cache
Referer: https://www.smes.go.kr/venturein/pbntc/searchVntrCmp
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
dnt: 1
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-gpc: 1