//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use types::company::{CompanyName, DartId, StockCode};
use types::YYYYMMDD;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "dart", table_name = "company_id")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub dart_id: DartId,
    #[sea_orm(column_type = "Text")]
    pub company_name: CompanyName,
    #[sea_orm(column_type = "Text")]
    pub stock_code: StockCode,
    pub id_modify_date: YYYYMMDD,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
