//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "dart", table_name = "filing")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub dart_id: String,
    #[sea_orm(column_type = "Text")]
    pub report_name: String,
    #[sea_orm(column_type = "Text")]
    pub receipt_number: String,
    #[sea_orm(column_type = "Text")]
    pub filer_name: String,
    pub receipt_date: Date,
    #[sea_orm(column_type = "Text")]
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
