[package]
name = "tracing-setup"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
