[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[[bench]]
name = "postgres"
harness = false

[dependencies]
diesel = { workspace = true, features = ["postgres", "r2d2", "time"] }
diesel_migrations = { workspace = true }
hashbrown = { workspace = true }
serde = { workspace = true, features = ["derive"] }
smes = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-native-tls", "macros", "postgres", "time", "derive"] }
thiserror = { workspace = true }
time = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["log"] }
utils = { workspace = true }

# Workspace crates
model = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
fake = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }
tracing-setup = { workspace = true }